 platform :ios, '9.0'

target 'sinaWeb' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sinaWeb

pod 'SnapKit'
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'YYModel'
pod 'pop'
pod 'YYText'
end
